modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Ridanisaurus/Emendatus-Enigmatica/issues"

[[mods]]
modId="emendatusenigmatica"
version="1.19.2-2.1.2"
displayName="Emendatus Enigmatica"
displayURL="https://github.com/Ridanisaurus/Emendatus-Enigmatica"
logoFile= "ee_logo.png"
credits='''
Thanks to Buuz135, MaxNeedsSnacks, Ellpeck, Mikey, and Darkere for their guidance and help on the development process.

Special thanks to all the people on Enigmatica Discord and NillerMedDild for their feedback, encouragement, and continues support on this journey.
'''
authors="Ridanisaurus"
description='''
This mod is a Data-Driven solution created for Modpack Developers to create their own materials, unify the look and feel of modded Minecraft, and provides them with a handful of feature generation options.

All blocks, and items have been properly tagged, and have all the basic recipes included upon their material's registration.

Additional information on how to setup new Materials, configure new Strata Blocks to be used for dynamic ores, and generating Deposit features can be found on the Wiki.
'''

[[dependencies.emendatusenigmatica]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.emendatusenigmatica]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "AFTER"
side = "BOTH"