# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Ridanisaurus/Emendatus-Enigmatica/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="emendatusenigmatica" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.16.3-1.0.1" #mandatory

# A display name for the mod
displayName="Emendatus Enigmatica" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/Ridanisaurus/Emendatus-Enigmatica" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

# A text field displayed in the mod UI
credits="Thanks to Buuz135, MaxNeedsSnacks, and Darkere for their guidance and help, and to all the people on Enigmatica Discord and NillerMedDild for their feedback, encouragement, continues support on this journey." #optional

# A text field displayed in the mod UI
authors="Ridanisaurus" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''This mod is created to help unifying some items, blocks, and ores that are common among other mods.
This mod provides little to no functionality as a stand-alone mod. It does however offer a wide range of options for Modpack authors to utilize these blocks, and items as a method of unification.
All blocks, and items have been properly tagged, and have all the basic recipes. This mod also includes a world gen of ores that match the strata provided by other mods such as Create and Quark.'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.emendatusenigmatica]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[32.0.98,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.emendatusenigmatica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"